// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databaseconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import databaseconnector.impl.JdbcConnector;

/**
 * For a more detailed documentation, please visit the website at
 * https://docs.mendix.com/appstore/connectors/database-connector
 * 
 * This Java action provides a consistent environment for Mendix projects to
 * perform arbitrary SQL statements on external relational databases.
 * 
 * Do not use this Java action for SELECT queries. This action returns the
 * number of affected rows.
 * 
 * JDBC (Java Database Connectivity) API, a standard Java API, is used when this
 * Java action attempts to connect to a Relational Database for which a JDBC driver
 * exists. The JDBC drivers for the databases you want to connect to must be placed
 * inside the userlib directory of your project.
 * 
 * The jdbcUrl argument must specify a database URL address that points to your
 * relational database and is dependent upon the particular database and JDBC
 * driver.
 * 
 * For example, 'jdbc:mysql://hostname/databaseName' can be used for MySQL
 * databases.
 * 
 * Note: Proper security is required when manually composing the statement text to
 *       avoid SQL injection.
 * 
 * @param jdbcUrl A database URL address that points to your database.
 * 
 * @param userName The user name for logging into the database.
 * 
 * @param password The password for logging into the database.
 * 
 * @param sql A string containing the SQL statement to be performed.
 * 
 * @return Number of affected rows.
 */
public class ExecuteStatement extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String jdbcUrl;
	private java.lang.String userName;
	private java.lang.String password;
	private java.lang.String sql;

	public ExecuteStatement(IContext context, java.lang.String jdbcUrl, java.lang.String userName, java.lang.String password, java.lang.String sql)
	{
		super(context);
		this.jdbcUrl = jdbcUrl;
		this.userName = userName;
		this.password = password;
		this.sql = sql;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return connector.executeStatement(jdbcUrl, userName, password, sql);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteStatement";
	}

	// BEGIN EXTRA CODE
	private final ILogNode logNode = Core.getLogger(this.getClass().getName());

	private final JdbcConnector connector = new JdbcConnector(logNode);
	// END EXTRA CODE
}
