// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databaseconnectortest.actions;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.webui.CustomJavaAction;

public class HasEqualListEntityValues extends CustomJavaAction<Boolean>
{
	private java.util.List<IMendixObject> Expected;
	private java.util.List<IMendixObject> Actual;

	public HasEqualListEntityValues(IContext context, java.util.List<IMendixObject> Expected, java.util.List<IMendixObject> Actual)
	{
		super(context);
		this.Expected = Expected;
		this.Actual = Actual;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
    return getMemberArray(Expected).equals(getMemberArray(Actual));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "HasEqualListEntityValues";
	}

	// BEGIN EXTRA CODE
  private List<?> getMemberArray(List<IMendixObject> mendixObjects) {
    return mendixObjects.stream().map(this::getMembers).collect(Collectors.toList());
  }

  private Map<String, ? extends IMendixObjectMember<?>> getMembers(IMendixObject mendixObject) {
    return mendixObject.getMembers(getContext());
  }

	// END EXTRA CODE
}
