// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databaseconnectortest.actions;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.webui.CustomJavaAction;
import databaseconnector.proxies.Row;

public class HasEqualListEntityValues extends CustomJavaAction<Boolean>
{
	private java.util.List<IMendixObject> __Expected;
	private java.util.List<databaseconnector.proxies.Row> Expected;
	private java.util.List<IMendixObject> __Actual;
	private java.util.List<databaseconnector.proxies.Row> Actual;

	public HasEqualListEntityValues(IContext context, java.util.List<IMendixObject> Expected, java.util.List<IMendixObject> Actual)
	{
		super(context);
		this.__Expected = Expected;
		this.__Actual = Actual;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.Expected = new java.util.ArrayList<databaseconnector.proxies.Row>();
		if (__Expected != null)
			for (IMendixObject __ExpectedElement : __Expected)
				this.Expected.add(databaseconnector.proxies.Row.initialize(getContext(), __ExpectedElement));

		this.Actual = new java.util.ArrayList<databaseconnector.proxies.Row>();
		if (__Actual != null)
			for (IMendixObject __ActualElement : __Actual)
				this.Actual.add(databaseconnector.proxies.Row.initialize(getContext(), __ActualElement));

		// BEGIN USER CODE
    return getMemberArray(Expected).equals(getMemberArray(Actual));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "HasEqualListEntityValues";
	}

	// BEGIN EXTRA CODE
  private List<?> getMemberArray(List<Row> list) {
    return list.stream().map(this::getMembers).collect(Collectors.toList());
  }

  private Map<String, ? extends IMendixObjectMember<?>> getMembers(Row a) {
    return a.getMendixObject().getMembers(getContext());
  }

	// END EXTRA CODE
}
