// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databaseconnectortest.actions;

import com.mendix.core.objectmanagement.member.MendixHashString;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class SetHashedValue extends CustomJavaAction<Boolean>
{
	private IMendixObject instance;
	private String member;
	private String hashedValue;

	public SetHashedValue(IContext context, IMendixObject instance, String member, String hashedValue)
	{
		super(context);
		this.instance = instance;
		this.member = member;
		this.hashedValue = hashedValue;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
	  MendixHashString hashStringMember = (MendixHashString) instance.getMember(getContext(), member);
	  hashStringMember.setInitialHash(hashedValue);

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SetHashedValue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
