// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databaseconnectortest.actions;

import java.util.function.Predicate;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive.PrimitiveType;
import com.mendix.webui.CustomJavaAction;

public class SetNullValues extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject instance;

	public SetNullValues(IContext context, IMendixObject instance)
	{
		super(context);
		this.instance = instance;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
	  instance.getMetaObject().getMetaPrimitives().stream()
	    .filter(isNotBoolean).filter(isNotHashString)
	    .forEach(p -> instance.setValue(getContext(), p.getName(), null));

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SetNullValues";
	}

	// BEGIN EXTRA CODE
	private Predicate<IMetaPrimitive> isNotBoolean = a -> a.getType() != PrimitiveType.Boolean;
	private Predicate<IMetaPrimitive> isNotHashString = a -> a.getType() != PrimitiveType.HashString;
	// END EXTRA CODE
}
