// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databaseconnectortest.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DatabaseConnectorTest module

	public static String getAwsAccessKey()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.AwsAccessKey");
	}

	public static String getAwsSecretKey()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.AwsSecretKey");
	}

	public static String getClusterAvailabilityZone()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterAvailabilityZone");
	}

	public static String getClusterIdentifier()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterIdentifier");
	}

	public static String getClusterNodeType()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterNodeType");
	}

	public static String getClusterPassword()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterPassword");
	}

	public static String getClusterRegion()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterRegion");
	}

	public static String getClusterType()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterType");
	}

	public static String getClusterUserName()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.ClusterUserName");
	}

	public static String getPostgreSQLAddress()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.PostgreSQLAddress");
	}

	public static String getPostgreSQLPassword()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.PostgreSQLPassword");
	}

	public static String getPostgreSQLUserName()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.PostgreSQLUserName");
	}

	public static String getVpcSecurityGroupId()
	{
		return (String)Core.getConfiguration().getConstantValue("DatabaseConnectorTest.VpcSecurityGroupId");
	}
}