// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittesting.proxies;

public enum UnitTestResult
{
	_1_Running(new String[][] { new String[] { "en_US", "Running" } }),
	_2_Failed(new String[][] { new String[] { "en_US", "Failed" } }),
	_3_Success(new String[][] { new String[] { "en_US", "Success" } });

	private java.util.Map<String,String> captions;

	private UnitTestResult(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
